const posts=JSON.parse(document.querySelector('#post-data').textContent);
let pending=false;function scrollState(){if(pending)return;pending=true;requestAnimationFrame(()=>{document.body.classList.toggle('scrolled',scrollY>70);document.documentElement.style.setProperty('--scroll',Math.min(scrollY,1000));document.documentElement.style.setProperty('--fade',Math.max(0,1-scrollY/500));pending=false;});}addEventListener('scroll',scrollState,{passive:true});scrollState();
const menu=document.querySelector('.mobile-menu');menu.addEventListener('click',e=>{if(e.target.closest('a'))menu.open=false;});document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.open=false;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.open){menu.open=false;menu.querySelector('summary').focus();}});
let currentPage=1;const pageSize=8;const select=document.querySelector('#category-select');const pagination=document.querySelector('.pagination');const items=[...document.querySelectorAll('[data-post]')];
function renderFeed(){const matches=posts.map((p,i)=>({p,i})).filter(({p})=>!select.value||p.categories.includes(select.value));const pages=Math.max(1,Math.ceil(matches.length/pageSize));currentPage=Math.min(currentPage,pages);const indices=new Set(matches.slice((currentPage-1)*pageSize,currentPage*pageSize).map(({i})=>i));items.forEach((el,i)=>el.hidden=!indices.has(i));document.querySelector('.empty').hidden=matches.length>0;pagination.hidden=pages<=1;pagination.querySelector('span').textContent=`${currentPage} / ${pages}`;pagination.querySelector('[data-page="previous"]').disabled=currentPage===1;pagination.querySelector('[data-page="next"]').disabled=currentPage===pages;}
select.addEventListener('change',()=>{currentPage=1;renderFeed();});pagination.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{currentPage+=button.dataset.page==='next'?1:-1;renderFeed();document.querySelector('#posts').scrollIntoView();}));renderFeed();
const dialog=document.querySelector('dialog'),input=document.querySelector('#search-input'),results=document.querySelector('.search-results');
function search(){const query=input.value.trim().toLowerCase();results.replaceChildren();const matches=posts.filter(p=>[p.title,p.desc,...p.categories,...p.tags].join(' ').toLowerCase().includes(query));matches.forEach(p=>{const a=document.createElement('a');a.href=p.url;a.textContent=p.title;const info=document.createElement('span');info.textContent=[p.date,...p.categories].join(' / ');a.append(info);results.append(a);});if(!matches.length){const empty=document.createElement('p');empty.textContent='没有找到相关文章。';results.append(empty);}}
document.querySelector('.search-open').addEventListener('click',()=>{menu.open=false;dialog.showModal();input.value='';search();input.focus();});document.querySelector('.search-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();dialog.close();}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});input.addEventListener('input',search);
