'use strict';
const {renderProfile} = require('./profile.cjs');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
module.exports=function renderHomepage({posts,base,cssVersion,jsVersion,profileVersion,categoryRoutes,tagRoutes}){
// Hexo normalizes config.url without a trailing slash, even when YAML has one.
base=base.replace(/\/+$/,'')+'/';
const url=(kind,value)=>(kind==='categories'?categoryRoutes:tagRoutes)[value];
const counts=key=>{const values=new Map();posts.forEach(p=>p[key].forEach(v=>values.set(v,(values.get(v)||0)+1)));return [...values].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));};
const categories=counts('categories'),tags=counts('tags');
const search='<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>';
const links=[['首页','#top'],['分类',base+'categories/'],['标签',base+'tags/'],['归档',base+'archives/'],['友链',base+'friends/'],['关于',base+'about/'],['学术主页','https://www.chenquan-tutu.top/']];
const navigation=()=>links.map(([name,href])=>`<a href="${href}"${name==='首页'?' aria-current="page"':''}>${name}</a>`).join('');
return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="canonical" href="${esc(base)}"><meta name="description" content="QQ 的博客。文章、笔记和项目。"><title>QQ’s blog</title><link rel="icon" href="/images/avatar.jpg"><link rel="preload" as="image" href="/images/cover.jpg"><link rel="stylesheet" href="/css/homepage.css?v=${cssVersion}"><link rel="stylesheet" href="/css/profile.css?v=${profileVersion}"><script src="/js/homepage.js?v=${jsVersion}" defer></script></head><body id="top"><a class="skip" href="#posts">跳到文章</a>
<header class="header"><a class="brand" href="#top"><img src="/images/avatar.jpg" alt="" width="30" height="30"><span>QQ’s blog</span></a><nav class="desktop-nav" aria-label="主导航">${navigation()}</nav><button class="search-open" aria-label="搜索文章">${search}</button><details class="mobile-menu"><summary>菜单 <span aria-hidden="true">☰</span></summary><nav aria-label="手机导航">${navigation()}</nav></details></header>
<section class="hero" aria-label="博客封面"><img class="cover" src="/images/cover.jpg" width="3000" height="1725" fetchpriority="high" alt="订制插画：兔子们在草地上野餐"><div class="cover-name"><h1>QQ’s blog</h1></div><a class="scroll-down" href="#posts" aria-label="浏览文章"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m5 9 7 7 7-7"/></svg></a></section>
<main class="reading"><div class="columns"><section id="posts" class="feed"><div class="feed-header"><h2>最新文章</h2><label class="category-filter"><span class="sr-only">筛选文章分类</span><select id="category-select"><option value="">全部分类</option>${categories.map(([c])=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label></div><div class="post-list">${posts.map((p,i)=>`<article class="post" data-post="${i}"><div class="post-meta"><time datetime="${p.date}">${p.date.replaceAll('-','.')}</time>${p.categories.map(c=>`<a href="${url('categories',c)}">${esc(c)}</a>`).join('')}</div><h3><a href="${p.url}">${esc(p.title)}</a></h3>${p.desc?`<p>${esc(p.desc)}</p>`:''}<div class="post-bottom"><div class="post-tags">${p.tags.map(t=>`<a href="${url('tags',t)}">#${esc(t)}</a>`).join('')}</div><a class="read" href="${p.url}">阅读全文</a></div></article>`).join('')}</div><p class="empty" hidden>这个分类下暂无文章。</p><nav class="pagination" aria-label="文章分页" hidden><button data-page="previous">上一页</button><span aria-live="polite"></span><button data-page="next">下一页</button></nav></section>
<aside class="sidebar"><section class="author">${renderProfile()}</section><section class="categories"><h2><a href="${base}categories/">分类</a></h2><ul>${categories.map(([c,count])=>`<li><a href="${url('categories',c)}"><span>${esc(c)}</span><small>${count}</small></a></li>`).join('')}</ul></section><section class="tags"><h2><a href="${base}tags/">标签</a></h2><div>${tags.map(([t])=>`<a href="${url('tags',t)}">${esc(t)}</a>`).join('')}</div></section><a class="archive-link" href="${base}archives/">全部归档 <span>${posts.length} 篇</span></a></aside></div>
<footer><span>© 2025–2026 QQ</span><a href="#top">回到顶部</a><a href="https://www.chenquan-tutu.top/">学术主页</a></footer></main>

<dialog aria-labelledby="search-title"><div class="dialog-heading"><h2 id="search-title">搜索文章</h2><button class="search-close" aria-label="关闭搜索">×</button></div><input id="search-input" type="search" placeholder="输入关键词" aria-label="搜索标题、摘要或标签"><div class="search-results" aria-live="polite"></div></dialog><script type="application/json" id="post-data">${JSON.stringify(posts).replace(/</g,'\\u003c')}</script></body></html>`;

};
